#!/usr/bin/env bash
# -*- bash -*-
#

if [[ "$OS" == "Linux" ]]; then
    install_package aspell
    install_package aspell-en
fi

if [[ "$OS" == "FreeBSD" ]]; then
    install_package aspell
    install_package bash-completion
    install_package en-aspell
    install_package python27
fi

if [[ "$OS" == "Darwin" ]]; then
    # Command line tools
    install_package aspell
    install_package bash-completion
    install_package brew-cask
    install_package duplicity
    install_package encfs
    install_package markdown
    install_package tree
	install_package wget
    
    # Software Packages from the internet
    install_package cask android-file-transfer
    install_package cask bittorrent-sync
    install_package cask google-chrome
    install_package cask java
    install_package cask osxfuse
    install_package cask skype
    install_package cask torbrowser
    install_package cask virtualbox
fi
